# Generated by Django 2.2.6 on 2019-11-04 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191104_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
