# Generated by Django 2.2.6 on 2019-11-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_map', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('upper_latitude', models.FloatField(default=0)),
                ('lower_latitude', models.FloatField(default=0)),
                ('left_longitude', models.FloatField(default=0)),
                ('right_longitude', models.FloatField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_map.Campus')),
            ],
            options={
                'verbose_name_plural': 'building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('map_img', models.ImageField(upload_to='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_map.Building')),
            ],
            options={
                'verbose_name_plural': 'floors',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='building_map.Floor')),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
    ]
