# Generated by Django 2.2.6 on 2019-11-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('campus_map', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upper_latitude', models.FloatField()),
                ('lower_latitude', models.FloatField()),
                ('left_longitude', models.FloatField()),
                ('right_longitude', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_map.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Pin')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
            bases=('account.pin',),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('map_img', models.ImageField(upload_to='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_map.Building')),
            ],
        ),
    ]
