# Generated by Django 2.2.6 on 2019-10-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('campus_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='건물명')),
                ('upper_latitude', models.FloatField()),
                ('lower_latitude', models.FloatField()),
                ('left_longtitude', models.FloatField()),
                ('right_longtitude', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_map.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('map_img', models.ImageField(upload_to='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_map.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Pin')),
                ('type', models.CharField(max_length=200, verbose_name='편의시설유형')),
                ('description', models.TextField(max_length=1000)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.pin',),
        ),
    ]
