# Generated by Django 2.2.6 on 2019-11-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='building_map.Floor'),
        ),
    ]
