# Generated by Django 2.2.6 on 2019-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0004_auto_20191103_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('PF', 'Purifier'), ('PR', 'Printer'), ('FE', 'Fire-Extinguisher')], default=None, max_length=2),
        ),
    ]
