# Generated by Django 2.2.6 on 2019-11-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0005_auto_20191103_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='building_map.Floor'),
        ),
    ]
