# Generated by Django 2.2.6 on 2019-11-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0006_auto_20191103_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='map_img',
        ),
        migrations.AddField(
            model_name='floor',
            name='map_image',
            field=models.ImageField(default='media/default_map.png', upload_to='media/building_map/'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='building_map.Building'),
        ),
    ]
