# Generated by Django 2.2.6 on 2019-11-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0007_auto_20191104_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('JS', '정수기'), ('IS', '인쇄기'), ('SH', '소화기'), ('HJ', '화장실'), ('SM', '수면실'), ('SS', '샤워실')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='floor',
            name='map_image',
            field=models.ImageField(default='default_map.png', upload_to='media/building_map/'),
        ),
    ]
