# Generated by Django 2.2.6 on 2019-11-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0009_auto_20191104_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='account.University'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('JSG', '정수기'), ('ISG', '인쇄기'), ('SHG', '소화기'), ('HJS', '화장실'), ('SMS', '수면실'), ('SWS', '샤워실')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='map_image',
            field=models.ImageField(default='default_map.png', upload_to='building_map/'),
        ),
    ]
