# Generated by Django 2.2.6 on 2019-11-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_map', '0012_auto_20191105_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility_type',
            new_name='facility_type',
        ),
    ]
